name: CI

on: [push, pull_request]

jobs:

  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install python3-pip

    - name: Dependency packages (pip)
      run: python3 -m pip install --user setuptools_scm

    - name: Set environment variables
      id: vars
      run: |
        echo "::set-output name=ver::$(make version)"

    - name: Build dist
      run: |
        P=greaseweazle-tools
        V=${{ steps.vars.outputs.ver }}
        make dist
        rm $P-$V.zip
        rm $P-$V/RELEASE_NOTES
        zip -r $P-$V.zip $P-$V

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: greaseweazle-tools.ci.${{ steps.vars.outputs.ver }}
        path: greaseweazle-tools-${{ steps.vars.outputs.ver }}.zip

  build-windows:
    runs-on: windows-2019
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x86

    - name: Dependency packages (pip)
      run: |
        python -m pip install --upgrade pip setuptools==60.1.0 wheel
        python -m pip install --user cx_Freeze setuptools_scm

    - name: Set environment variables
      id: vars
      run: |
        echo "::set-output name=ver::$(make version)"

    - name: Build dist
      run: |
        $P="greaseweazle-tools"
        $V="${{ steps.vars.outputs.ver }}"
        make dist
        rm $P-$V.zip
        rm $P-$V/RELEASE_NOTES
        make _windist

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: greaseweazle-tools.ci.${{ steps.vars.outputs.ver }}
        path: greaseweazle-tools-${{ steps.vars.outputs.ver }}-win.zip

  finalise:
    needs: [build-ubuntu, build-windows]
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install python3-pip

    - name: Dependency packages (pip)
      run: python3 -m pip install --user setuptools_scm

    - name: Set environment variables
      id: vars
      run: |
        echo "::set-output name=ver::$(make version)"

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: greaseweazle-tools.ci.${{ steps.vars.outputs.ver }}

    - name: Fix up Windows distribution
      run: |
        P=greaseweazle-tools
        V=${{ steps.vars.outputs.ver }}
        unzip $P-$V-win.zip
        find $P-$V -name 'api-ms-*' | xargs rm -f
        find $P-$V/lib -name 'python*.dll' | xargs rm -f
        find $P-$V/lib -name 'vcruntime140.dll' | xargs rm -f
        rm $P-$V-win.zip
        zip -r $P-$V-win.zip $P-$V

    - name: Upload finalised artifacts
      uses: actions/upload-artifact@v2
      with:
        name: greaseweazle-tools.ci.${{ steps.vars.outputs.ver }}
        path: greaseweazle-tools-${{ steps.vars.outputs.ver }}-win.zip
