on:
  push:
    tags:
    - 'v*.*'

name: Release

jobs:

  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install git python3-pip zip

    - name: Dependency packages (pip)
      run: python3 -m pip install --user setuptools_scm

    - name: Set environment variables
      id: vars
      run: |
        echo "ver=$(make version)" >> $GITHUB_OUTPUT

    - name: Build dist
      run: make dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: greaseweazle.ci.${{ steps.vars.outputs.ver }}
        path: greaseweazle-${{ steps.vars.outputs.ver }}.zip

  build-win32:
    runs-on: windows-2019
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        architecture: x86

    - name: Dependency packages (pip)
      run: |
        python -m pip install --upgrade pip setuptools==60.1.0 wheel
        python -m pip install --user cx_Freeze setuptools_scm

    - name: Set environment variables
      id: vars
      shell: bash
      run: |
        echo "ver=$(make version)" >> $GITHUB_OUTPUT

    - name: Build dist
      shell: bash
      run: |
        export GW=greaseweazle-${{ steps.vars.outputs.ver }}
        make windist
        curl -L http://softpres.org/_media/files:spsdeclib_5.1_windows.zip --output ipf.zip
        7z x -oipf ipf.zip
        cp -a ipf/capsimg_binary/CAPSImg.dll $GW/
        rm -rf ipf ipf.zip
        7z a $GW-win32.zip $GW

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: greaseweazle.ci.${{ steps.vars.outputs.ver }}
        path: greaseweazle-${{ steps.vars.outputs.ver }}-win32.zip

  build-win64:
    runs-on: windows-2022
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: x64

    - name: Dependency packages (pip)
      run: |
        python -m pip install --upgrade pip setuptools==60.1.0 wheel
        python -m pip install --user cx_Freeze setuptools_scm

    - name: Set environment variables
      id: vars
      shell: bash
      run: |
        echo "ver=$(make version)" >> $GITHUB_OUTPUT

    - name: Build dist
      shell: bash
      run: |
        export GW=greaseweazle-${{ steps.vars.outputs.ver }}
        make windist
        curl -L http://softpres.org/_media/files:spsdeclib_5.1_windows.zip --output ipf.zip
        7z x -oipf ipf.zip
        cp -a ipf/capsimg_binary/x64/CAPSImg.dll $GW/
        rm -rf ipf ipf.zip
        7z a $GW-win64.zip $GW

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: greaseweazle.ci.${{ steps.vars.outputs.ver }}
        path: greaseweazle-${{ steps.vars.outputs.ver }}-win64.zip

  finalise:
    needs: [build-ubuntu, build-win32, build-win64]
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Dependency packages (apt)
      run: |
        sudo apt update
        sudo apt -y install git python3-pip zip

    - name: Dependency packages (pip)
      run: python3 -m pip install --user setuptools_scm

    - name: Set environment variables
      id: vars
      run: |
        echo "ver=$(make version)" >> $GITHUB_OUTPUT

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: greaseweazle.ci.${{ steps.vars.outputs.ver }}

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Greaseweazle Tools ${{ steps.vars.outputs.ver }}
        body: "[**Release Notes:**](https://github.com/keirf/greaseweazle/blob/master/RELEASE_NOTES)"
        draft: false
        prerelease: false
        artifacts: "greaseweazle-${{ steps.vars.outputs.ver }}-win64.zip,greaseweazle-${{ steps.vars.outputs.ver }}-win32.zip,greaseweazle-${{ steps.vars.outputs.ver }}.zip"
        artifactContentType: application/zip
